### ISSUE TITLE
PHP 7 Requirement

### ISSUE THREAD

**Issue by tricki** [ConsoleTVs/Identify#1]
Because of the usage of [return type declarations](http://php.net/manual/en/migration70.new-features.php#migration70.new-features.return-type-declarations) this package can only be used on PHP 7+.

Example: https://github.com/ConsoleTVs/Identify/blob/master/src/IdentifyServiceProvider.php#L33

This either needs to be removed / moved to a separate branch or at least mentioned in the readme.

**Comment by ConsoleTVs** [comment]
Fixed, thanks for pointing it out!
