### ISSUE TITLE
Not compatible with Laravel 5.4 [ #My Mistake, It works ] 

### ISSUE THREAD

**Issue by leandrit1** [ConsoleTVs/Identify#2]
Hi,

Is there a way to update this package for Laravel 5.4. It would be very helpful for me.

Thank you

**Comment by ConsoleTVs** [comment]
It's already compatible, what error do you get?

**Comment by leandrit1** [comment]
C:\laragon-wamp\www\laraApp (feature/AUG23-PassportAccess)
λ composer require consoletvs/identify
Using version ^1.3 for consoletvs/identify
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.4.32
    - Conclusion: don't install laravel/framework v5.4.32
    - unicodeveloper/laravel-identify 1.1.0 requires illuminate/support 5.2.* -> satisfiable by illuminate/support[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - unicodeveloper/laravel-identify 1.1.1 requires illuminate/support 5.2.* -> satisfiable by illuminate/support[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - don't install illuminate/support v5.2.0|don't install laravel/framework v5.4.32
    - don't install illuminate/support v5.2.19|don't install laravel/framework v5.4.32
    - don't install illuminate/support v5.2.21|don't install laravel/framework v5.4.32
    - don't install illuminate/support v5.2.24|don't install laravel/framework v5.4.32
    - don't install illuminate/support v5.2.25|don't install laravel/framework v5.4.32
    - don't install illuminate/support v5.2.26|don't install laravel/framework v5.4.32
    - don't install illuminate/support v5.2.27|don't install laravel/framework v5.4.32
    - don't install illuminate/support v5.2.28|don't install laravel/framework v5.4.32
    - don't install illuminate/support v5.2.31|don't install laravel/framework v5.4.32
    - don't install illuminate/support v5.2.32|don't install laravel/framework v5.4.32
    - don't install illuminate/support v5.2.37|don't install laravel/framework v5.4.32
    - don't install illuminate/support v5.2.43|don't install laravel/framework v5.4.32
    - don't install illuminate/support v5.2.45|don't install laravel/framework v5.4.32
    - don't install illuminate/support v5.2.6|don't install laravel/framework v5.4.32
    - don't install illuminate/support v5.2.7|don't install laravel/framework v5.4.32
    - Installation request for laravel/framework (locked at v5.4.32, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.32].
    - Installation request for unicodeveloper/laravel-identify 1.1.* -> satisfiable by unicodeveloper/laravel-identify[1.1.0, 1.1.1].


Installation failed, reverting ./composer.json to its original content.

**Comment by ConsoleTVs** [comment]
I dont know why is trying to install unicodeveloper/laravel-identify. Its not requires in this package composer.json. you can check that the composer.json in this package reqyired illuminate/support 5.*. Not 5.2.*. Something is wrong on ur side...

**Comment by leandrit1** [comment]
Ah, sorry, I was trying that package as first option and it seems that I did not remove it from composer.
My mistake, sorry for the trouble.

Thanks for taking the time to reply and also for this great package.

**Comment by ConsoleTVs** [comment]
Perfect!
